# Generated by Django 4.2.7 on 2023-11-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0004_teasubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tea_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fms.teasubmission')),
            ],
        ),
    ]
