# Generated by Django 4.2.7 on 2023-11-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
