# Generated by Django 4.2.7 on 2023-11-28 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0006_payment_rate_per_kg_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tea_submission',
        ),
        migrations.AddField(
            model_name='payment',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fms.farmer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='monthly_period',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
