# Generated by Django 4.2.7 on 2023-11-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0007_remove_payment_tea_submission_payment_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
