# Generated by Django 4.2.7 on 2023-11-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0008_payment_deduction_amount_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='max_salary_advance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='nhif_rate',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='nssf_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
