# Generated by Django 4.2.7 on 2023-11-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0009_payment_max_salary_advance_payment_nhif_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='max_salary_advance',
            field=models.DecimalField(decimal_places=2, default=7000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='nhif_rate',
            field=models.DecimalField(decimal_places=2, default=750, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='nssf_rate',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
