# Generated by Django 4.2.7 on 2023-11-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0010_alter_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='max_salary_advance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='nhif_rate',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='nssf_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_taken', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_taken', models.DateField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fms.farmer')),
            ],
        ),
    ]
