# Generated by Django 4.2.7 on 2023-11-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0013_teasubmission_field_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teasubmission',
            name='field_manager',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teasubmission',
            name='submission_date',
            field=models.DateField(),
        ),
    ]
