# Generated by Django 4.2.7 on 2023-11-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0015_alter_teasubmission_field_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teasubmission',
            name='submission_date',
        ),
    ]
